package objects;

public enum OBJECTID {

	MENU, NULL,

	// CHARACTERS
	DISPLAYER, PLAYER, FOE,

	// WORLD //
	WALL, DECOR, DESTROYABLE, FLAG, LOOT,
	// puzzler
	CASE, COMPUTER, DOOR, WALLCRACKED,

	// PUZZLE //
	PROCESSOR,

	TIMER,
	
	P_BOMB, P_CARD, P_CARDFOLDER, P_VIRUS, P_KEY, P_LOCK, P_WORD, P_WORDFOLDER;

}
